name: 'Get Current Commit Sha'
description: 'Get current commit sha and print it '
runs:
  using: 'composite'
  steps:
    - name: Get Comit sha
      id: custom_action_commit_sha_get
      run: "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV  
