name: Test second workflow 
on:
  push:
    branches:
      - main
jobs:
  example_job_for_test:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        id: first-step
        run: echo "Hello for first step"   
